feat: Update subseries presentation
ietf-tools/xml2rfc pull request #1102
Opened 2024-02-14 07:13 UTC by kesara

Fixes #1100

Examples:
| Format | Example |
| --- | --- |
| XML | [draft-foobar-00.xml](https://t4.fq.nz/subseries-reference/draft-foobar-00.xml) |
| Text | [draft-foobar-00.txt](https://t4.fq.nz/subseries-reference/draft-foobar-00.txt) |
| HTML | [draft-foobar-00.html](https://t4.fq.nz/subseries-reference/draft-foobar-00.html) |
| PDF | [draft-foobar-00.pdf](https://t4.fq.nz/subseries-reference/draft-foobar-00.pdf) |

2024-02-14 16:10 UTC, ajeanmahoney commented
This fix's [HTML output](https://t4.fq.nz/subseries-reference/draft-foobar-00.html) matches the current HTML output.  However, the [text output](https://t4.fq.nz/subseries-reference/draft-foobar-00.txt) has line breaks in the URLs, whereas the current layout for text output starts the URL on a new line to prevent some of these breaks.

2024-02-14 16:19 UTC, cabo commented
(off-topic comment: This appears to be one more case where <nobr functionality would help, this time in the bowels of xml2rfc.)

2024-02-14 23:17 UTC, kesara commented
> This fix's [HTML output](https://t4.fq.nz/subseries-reference/draft-foobar-00.html) matches the current HTML output. However, the [text output](https://t4.fq.nz/subseries-reference/draft-foobar-00.txt) has line breaks in the URLs, whereas the current layout for text output starts the URL on a new line to prevent some of these breaks.

@ajeanmahoney, I've made appropriate changes. Can you recheck the example outputs? Thanks.

2024-02-16 22:45 UTC, rjsparks approved these changes

2024-02-16 22:45 UTC, rjsparks commented
I've approved, but wait for @ajeanmahoney review as well.

2024-02-16 23:41 UTC, ajeanmahoney requested changes
The text output is missing a period between the URL and the "At the time of writing" sentence (the period is there in the HTML and PDF outputs). 

The extrapolated URL (when the target is not given) for a STD, BCP, or FYI should be of the form `<https://www.rfc-editor.org/info/...>`. Currently it shows, for example, `<https://www.rfc-editor.org/std/std1>`

For the non-subseries referencegroup output, I'd like to see one that contains multiple references, both with and without a target, thanks!

2024-02-19 01:28 UTC, kesara commented
> The text output is missing a period between the URL and the "At the time of writing" sentence (the period is there in the HTML and PDF outputs).
> 

I've fixed this.

> The extrapolated URL (when the target is not given) for a STD, BCP, or FYI should be of the form `<https://www.rfc-editor.org/info/...>`. Currently it shows, for example, `<https://www.rfc-editor.org/std/std1>`
> 

I've fixed this too.

> For the non-subseries referencegroup output, I'd like to see one that contains multiple references, both with and without a target, thanks!

See updated files:
| Format | Example |
| --- | --- |
| XML | [draft-foobar-00.xml](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.xml) |
| Text | [draft-foobar-00.txt](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.txt) |
| HTML | [draft-foobar-00.html](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.html) |
| PDF | [draft-foobar-00.pdf](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.pdf) |

2024-02-19 05:19 UTC, cabo commented
Can you do an example that has a referencegroup mixed from references to different subseries?

2024-02-19 07:14 UTC, kesara commented
> Can you do an example that has a referencegroup mixed from references to different subseries?

@cabo, RPC confirmed that RFCs are not shared between different subseries.
But this is an issue if this happens in the future because the `xml2rfc` logic looks at the first reference within `referencegroup` to identify the subseries.
This is because `referencegroup` element doesn't carry information about the subseries.

2024-02-19 07:45 UTC, cabo commented
I'm fine with this behavior (first reference determines processing) -- I just wanted to make sure that we have considered this (non-)use case.

2024-02-20 18:48 UTC, kesara commented
@ajeanmahoney Any issues with the output changes in https://github.com/ietf-tools/xml2rfc/pull/1102#issuecomment-1951542113?

2024-02-21 21:12 UTC, ajeanmahoney approved these changes
I've reviewed the test outputs, and it looks good.

2024-02-21 21:37 UTC, merged